name: 'Generate Build Results'
description: 'Generate build results in Markdown format.'

branding:
  icon: 'align-left'
  color: 'orange'

inputs:
  build-results-json:
    description: 'Build results in JSON format.'
    type: string
    required: true

outputs:
  build-results-md:
    description: 'Build results in Markdown format.'
  build-results-md-json:
    description: 'Build results in Markdown format (JSON stringified).'
  build-results-md-json-text:
    description: 'Build results in Markdown format (JSON stringified, without quotes).'

runs:
  using: node20
  main: dist/index.js
